# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yongfeng Zhao's Home Page
title_cn: 赵永峰的主页
author: Yongfeng Zhao
author_cn: 赵永峰
email: yfzhao2021@suda.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Associate professor,
  Center for Soft Condensed Matter Physics and Interdisciplinary Research,
  School of Physical Science and Technology,
  Soochow University, 
  Suzhou, China.
description_cn: >- # this means to ignore newlines until "baseurl:"
  副教授，软凝聚态物理及交叉研究中心，物理科学与技术学院，苏州大学，苏州，中国
baseurl: "" # the subpath of your site, e.g. /blog
url: "zhaoyongfeng1990.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zhaoyongfeng1990

# Build settings
markdown: kramdown
theme: minima
# remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  #- jekyll-remote-theme

url: "https://zhaoyongfeng1990.github.io"
google_analytics: G-TSF6N00LN4
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
